spring.application.name=customer_insights

# MS SQL Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=customer_insights_db;encrypt=false
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true